use_frameworks!

target 'SCSearchBar_Example' do
  pod 'SCSearchBar', :path => '../'

  target 'SCSearchBar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
